
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcwwvgqtovejkzpzilpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jd3d2Z3F0b3Zlamt6cHppbHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTU1NTcsImV4cCI6MjA1OTc5MTU1N30.LpY26gtYKDFIvYuLIK1983ycXM8swprZZUN9JU2DwDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase-auth',
  }
});
